#!/bin/sh
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOF
CREATE USER $POSTGRES_USER_WEB WITH PASSWORD '$POSTGRES_USER_WEB_PASSWORD';
CREATE DATABASE $POSTGRES_DB;
GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER_WEB;
-- Extensions init
\connect $POSTGRES_DB
EOF
